baseurl = "/"
title = "Kauê Braga"

languagecode = "en"
defaultcontentlanguage = "en"
DefaultContentLanguageInSubdir = false

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

theme = "hugo-coder"

paginate = 20
canonifyurls = true

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "yourdiscussshortname"

[markup.goldmark.renderer]
unsafe= true

[params]
    author = "Kauê Braga"
    description = "My personal website"
    keywords = "blog,developer,personal"
    info = "Cities • Data • Transport • R"
    avatarurl = "images/my_photo.jpg"
    #gravatar = "john.doe@example.com"
    # footercontent = "Cientista de dados buscando trabalhos de consultoria"

    dateformat = "January 2, 2006"

    hideFooter = false
    hideCredits = false
    hideCopyright = true
    since = 2019

    # Git Commit in Footer, uncomment the line below to enable it.
    commit = "https://github.com/luizdepra/hugo-coder/tree/"

    rtl = false

    # Specify light/dark colorscheme
    # Supported values:
    # "auto" (use preference set by browser)
    # "dark" (dark background, light foreground)
    # "light" (light background, dark foreground) (default)
    colorscheme = "light"

    # Series see also post count
    maxSeeAlsoItems = 5

    # Enable Twemoji
    enableTwemoji = true

    # Custom CSS
    customCSS = ["css/custom.css"]

    # Custom JS
    customJS = ["js/accordion.js"]

# If you want to use fathom(https://usefathom.com) for analytics, add this section
[params.fathomAnalytics]
    siteID = "ABCDE"
    # Default value is cdn.usefathom.com, overwrite this if you are self-hosting
    serverURL = "analytics.example.com"

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[[params.social]]
    name = "Email"
    icon = "fa fa-envelope"
    weight = 1
    url = "mailto:kaue@kauebraga.dev"
[[params.social]]
    name = "Github"
    icon = "fab fa-github"
    weight = 2
    url = "https://github.com/kauebraga/"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter"
    weight = 3
    url = "https://twitter.com/ckauebraga/"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin"
    weight = 4
    url = "https://www.linkedin.com/in/kauebraga/"


[languages]
    [languages.en]
        languagename = "English"

        [languages.en.menu]

            [[languages.en.menu.main]]
            name = "About me"
            weight = 1
            url = "about/"

            [[languages.en.menu.main]]
            name = "My work"
            weight = 2
            url = "experience/"

            # [[languages.en.menu.main]]
            # name = "Blog"
            # weight = 2
            # url = "posts/"

            [[languages.en.menu.main]]
            name = "Projects"
            weight = 3
            url = "projects/"

            # [[languages.en.menu.main]]
            # name = "Publications"
            # weight = 4
            # url = "/en/publications/"
			

            [[languages.en.menu.main]]
            name = "Consulting"
            weight = 5
            url = "consulting/"

            # [[languages.en.menu.main]]
            # name = "Contact me"
            # weight = 6
            # url = "/en/contact/"


    [languages.pt-br]
        languagename = "Português"
        title = "Kauê Braga"

        [languages.pt-br.params]
            author = "Kauê Braga"
            info = "Cidades • Dados • Gráficos • Mapas • R"
            # bonito = "Interseção entre engenharia de transporte e ciência de dados"
            description = "Meu site pessoal"
            keywords = "blog,desenvolvedor,pessoal"
            # footercontent = "Coloque algum texto aqui."

        [languages.pt-br.menu]

            [[languages.pt-br.menu.main]]
            name = "Sobre"
            weight = 1
            url = "about/"

            # [[languages.pt-br.menu.main]]
            # name = "Blog"
            # weight = 2
            # url = "posts/"
            
            
            [[languages.pt-br.menu.main]]
            name = "Meu trabalho"
            weight = 2
            url = "my_work/"


            [[languages.pt-br.menu.main]]
            name = "Projetos"
            weight = 3
            url = "projects/"
            
            
            [[languages.pt-br.menu.main]]
            name = "Blog"
            weight = 4
            url = "posts/"
            
            # [[languages.pt-br.menu.main]]
            # name = "Teste"
            # weight = 4
            # url = "map/"
            
            # [[languages.pt-br.menu.main]]
            # name = "Consultoria"
            # weight = 4
            # url = "consulting/"

            # [[languages.pt-br.menu.main]]
            # name = "Contato"
            # weight = 5
            # url = "contact/"